# Generated automatically from Makefile.in by configure.
# Copyright (C) 2001  MandrakeSoft S.A.
#
#   MandrakeSoft S.A.
#   43, rue d'Aboukir
#   75002 Paris - France
#   http://www.linux-mandrake.com/
#   http://www.mandrakesoft.com/
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307 USA
#
####################################################
# NOTE: To be compatibile with nmake (microsoft vc++) please follow
# the following rules:
#   use $(VAR) not ${VAR}

VERSION=1.2
VER_STRING=1.2
REL_STRING=June 3, 2001
PREFIX=/usr/local/bochs
MANPATH=/usr/man
MAN_PAGE_LIST=bochs bochsrc bximage bochs-dlx
BINPATH=/usr/local/bin
INSTALL_LIST=bios/BIOS-* CHANGES COPYING README bios/VGABIOS* bochs bximage
INSTALL_LIST_SED=DOC-linux.html
BOCHS_SCRIPTS=bochs-dlx bochs-docs
CP=cp
CAT=cat
RM=rm
MV=mv
LN_S=ln -sf
DLXLINUX_TAR=dlxlinux2.tar.gz
DLXLINUX_TAR_URL=http://bochs.sourceforge.net/guestos/$(DLXLINUX_TAR)
DLXLINUX_ROMFILE=BIOS-bochs-latest
GUNZIP=gunzip
WGET=wget
SED=sed
SOURCES=/usr/src/redhat/SOURCES
SPECS=/usr/src/redhat/SPECS
RPMS=/usr/src/redhat/RPMS
SRPMS=/usr/src/redhat/SRPMS
MKDIR=mkdir
RMDIR=rmdir
TAR=tar
RPM=rpm
CHMOD=chmod
CHOWN=chown

.SUFFIXES: .cc


SHELL = /bin/sh




CC = gcc
CXX = c++
CFLAGS = -ggdb3 -O0 $(MCH_CFLAGS) $(FLA_FLAGS)
CXXFLAGS = -ggdb3 -O0 $(MCH_CFLAGS) $(FLA_FLAGS)

LDFLAGS = -lX11  
LIBS = 
# To compile with readline:
#   linux needs just -lreadline
#   solaris needs -lreadline -lcurses
X_LIBS = 
X_PRE_LIBS = 
GUI_LINK_OPTS_X = $(X_LIBS) $(X_PRE_LIBS) -lX11
GUI_LINK_OPTS_BEOS = -lbe
GUI_LINK_OPTS_RFB = 
GUI_LINK_OPTS_WIN32 = -luser32 -lgdi32 -lwinmm -lcomdlg32 -lcomctl32
GUI_LINK_OPTS_WIN32_VCPP = user32.lib gdi32.lib winmm.lib \
  comdlg32.lib comctl32.lib wsock32.lib
GUI_LINK_OPTS_MACOS =
GUI_LINK_OPTS_NOGUI =
GUI_LINK_OPTS_TERM = 
GUI_LINK_OPTS = $(GUI_LINK_OPTS_X)
RANLIB = ranlib

BX_INCDIRS = -I. -Iinstrument/stubs

MDEFINES = CC="$(CC)" CXX="$(CXX)" CFLAGS="$(CFLAGS)" CXXFLAGS="$(CXXFLAGS)" \
  LDFLAGS="$(LDFLAGS)" LIBS="$(LIBS)" \
  X_LIBS="$(X_LIBS)" X_PRE_LIBS="$(X_PRE_LIBS)" \
  prefix="$(prefix)" exec_prefix="$(exec_prefix)" \
  bindir="$(bindir)" infodir="$(infodir)"

#SUBDIRS = iodev debug

#all install uninstall: config.h#
#        for subdir in $(SUBDIRS); do #
#          echo making $@ in $$subdir; #
#          (cd $$subdir && $(MAKE) $(MDEFINES) $@) || exit 1; #
#        done#



# gnu flags for clean up
#CFLAGS  = -ansi -O -g -Wunused -Wuninitialized


NONINLINE_OBJS = \
	main.o \
	load32bitOShack.o \
	state_file.o \
	pc_system.o \
	osdep.o

EXTERN_ENVIRONMENT_OBJS = \
	main.o \
	load32bitOShack.o \
	state_file.o \
	pc_system.o

DEBUGGER_LIB   = debug/libdebug.a
DISASM_LIB     = disasm/libdisasm.a
DYNAMIC_LIB    = dynamic/libdynamic.a
INSTRUMENT_LIB = instrument/stubs/libinstrument.a
FPU_LIB        = fpu/libfpu.a
READLINE_LIB   = 

BX_OBJS = $(NONINLINE_OBJS)

BX_INCLUDES = bochs.h config.h osdep.h


.cc.o:
	$(CXX) -c $(CXXFLAGS) $(BX_INCDIRS) $< -o $@
.c.o:
	$(CC) -c $(CFLAGS) $(FPU_FLAGS) $(BX_INCDIRS) $< -o $@


all: bochs  bximage




bochs: iodev/libiodev.a  \
           cpu/libcpu.a memory/libmemory.a gui/libgui.a \
              $(BX_OBJS) \
           $(SIMX86_OBJS) \
           $(FPU_LIB)
	$(CXX) -o $@ $(CXXFLAGS) $(BX_OBJS) \
                $(SIMX86_OBJS) \
		iodev/libiodev.a \
		cpu/libcpu.a memory/libmemory.a gui/libgui.a \
		    \
		$(FPU_LIB) \
		$(GUI_LINK_OPTS) \
		$(MCH_LINK_FLAGS) \
	        $(SIMX86_LINK_FLAGS) \
		$(READLINE_LIB)

bximage: misc/bximage.o
	$(CXX) -o $@ $(CXXFLAGS) misc/bximage.o

$(BX_OBJS): $(BX_INCLUDES)

bxversion.h::
	$(RM) -f bxversion.h
	echo '// This file is generated by "make bxversion.h"' > bxversion.h
	echo "#define VER_STRING \"$(VER_STRING)\"" >> bxversion.h
	echo "#define REL_STRING \"$(REL_STRING)\"" >> bxversion.h

iodev/libiodev.a::
	cd iodev && \
	$(MAKE) $(MDEFINES) libiodev.a
	echo done

debug/libdebug.a::
	cd debug && \
	$(MAKE) $(MDEFINES) libdebug.a
	echo done

cpu/libcpu.a::
	cd cpu && \
	$(MAKE) $(MDEFINES) libcpu.a
	echo done

memory/libmemory.a::
	cd memory && \
	$(MAKE) $(MDEFINES) libmemory.a
	echo done

gui/libgui.a::
	cd gui && \
	$(MAKE) $(MDEFINES) libgui.a
	echo done

disasm/libdisasm.a::
	cd disasm && \
	$(MAKE) $(MDEFINES) libdisasm.a
	echo done

dynamic/libdynamic.a::
	cd dynamic && \
	$(MAKE) $(MDEFINES) libdynamic.a
	echo done

instrument/stubs/libinstrument.a::
	cd instrument/stubs && \
	$(MAKE) $(MDEFINES) libinstrument.a
	echo done

fpu/libfpu.a::
	cd fpu && \
	$(MAKE) $(MDEFINES) libfpu.a
	echo done

libbochs.a:
	-rm -f libbochs.a
	ar rv libbochs.a $(EXTERN_ENVIRONMENT_OBJS)
	$(RANLIB) libbochs.a

libbochs_cpu.a:  $(BX_OBJS)
	-rm -f libbochs_cpu.a
	ar rv libbochs_cpu.a $(BX_OBJS)
	$(RANLIB) libbochs_cpu.a

install: all install_bin install_man install_dlx

install_bin::
	-mkdir $(PREFIX)
	-mkdir $(PREFIX)/$(VERSION)
	test -d $(PREFIX)/$(VERSION)
	test -w $(PREFIX)/$(VERSION)
	for i in $(BOCHS_SCRIPTS); do cat build/linux/$$i | $(SED) -e 's/@VERSION@/$(VERSION)/g' > $(BINPATH)/$$i; $(CHMOD) 755 $(BINPATH)/$$i; done
	for i in $(INSTALL_LIST_SED); do cat build/linux/$$i | $(SED) -e 's/@VERSION@/$(VERSION)/g' > $(PREFIX)/$(VERSION)/$$i; $(CHMOD) 644 $(PREFIX)/$(VERSION)/$$i; done
	for i in $(INSTALL_LIST); do /bin/cp $$i $(PREFIX)/$(VERSION); done
	$(LN_S) $(PREFIX)/$(VERSION)/bochs $(BINPATH)/bochs
	$(LN_S) $(PREFIX)/$(VERSION)/bximage $(BINPATH)/bximage
	$(CP) -r docs-html $(PREFIX)/$(VERSION)
	$(RM) -f $(PREFIX)/$(VERSION)/README
	$(CAT) build/linux/README.linux-binary README > $(PREFIX)/$(VERSION)/README
	$(CP) font/vga.pcf $(PREFIX)/$(VERSION)
	$(CP) .bochsrc $(PREFIX)/$(VERSION)/bochsrc-sample.txt
	$(RM) -f $(PREFIX)/latest
	$(LN_S) $(VERSION) $(PREFIX)/latest

install_man::
	for i in $(MAN_PAGE_LIST); do cat doc/man/$$i.1 | $(SED) -e 's/@VERSION@/$(VERSION)/g' > $(MANPATH)/man1/$$i.1; chmod 644 $(MANPATH)/man1/$$i.1; done

install_dlx::
	$(RM) -f $(DLXLINUX_TAR)
	$(WGET) $(DLXLINUX_TAR_URL)
	$(RM) -rf $(PREFIX)/dlxlinux
	$(GUNZIP) -c $(DLXLINUX_TAR) | (cd $(PREFIX); tar -xvf -)
	$(RM) -f $(DLXLINUX_TAR)
	test -d $(PREFIX)/dlxlinux
	(cd $(PREFIX)/dlxlinux; $(MV) bochsrc.txt bochsrc.txt.orig; $(SED) -e "s/1\.1\.2/$(VERSION)/g"< bochsrc.txt.orig > bochsrc.txt; rm -f bochsrc.txt.orig)
	$(CHOWN) -R root.root $(PREFIX)/dlxlinux
	$(CHMOD) 777 $(PREFIX)/dlxlinux
	$(CHMOD) 666 $(PREFIX)/dlxlinux/*
	$(CHMOD) 644 $(PREFIX)/dlxlinux/README

erase_install::
	$(RM) -rf $(PREFIX)/$(VERSION)
	$(RM) -rf $(PREFIX)/dlxlinux
	$(RM) -rf $(PREFIX)/latest
	-$(RMDIR) $(PREFIX)
	for i in $(MAN_PAGE_LIST); do $(RM) -f $(MANPATH)/man1/$$i.1; done

rpm:: dist-clean
	test -w $(SOURCES)
	test -w $(SPECS)
	rm -f /usr/src/redhat/SPECS/bochs.spec
	$(CAT) build/linux/bochs.rpmspec.template | $(SED) "s/@VERSION@/$(VERSION)/g" > $(SPECS)/bochs.spec
	$(RM) -rf $(SOURCES)/bochs
	$(MKDIR) $(SOURCES)/bochs
	$(TAR) cf - * .??* | (cd $(SOURCES)/bochs && tar xf -)
	(cd $(SOURCES); tar czf bochs.tar.gz bochs)
	$(RPM) -ba $(SPECS)/bochs.spec

clean:
	rm -f  *.o
	rm -f  */*.o
	rm -f  *.a
	rm -f  */*.a
	rm -f  bochs
	rm -f  bximage
	rm -f  bochs.out
	rm -f  bochsout.txt

local-dist-clean: clean
	rm -f  config.h config.status config.log config.cache

all-clean: clean
	cd iodev && \
	$(MAKE) clean
	echo done
	cd debug && \
	$(MAKE) clean
	echo done
	cd cpu && \
	$(MAKE) clean
	echo done
	cd memory && \
	$(MAKE) clean
	echo done
	cd gui && \
	$(MAKE) clean
	echo done
	cd disasm && \
	$(MAKE) clean
	echo done
	cd instrument/stubs && \
	$(MAKE) clean
	echo done
	cd misc && \
	$(MAKE) clean
	echo done
	cd dynamic && \
	$(MAKE) clean
	echo done
	cd fpu && \
	$(MAKE) clean
	echo done

dist-clean: local-dist-clean
	cd iodev && \
	$(MAKE) dist-clean
	echo done
	cd debug && \
	$(MAKE) dist-clean
	echo done
	cd bios && \
	$(MAKE) dist-clean
	echo done
	cd cpu && \
	$(MAKE) dist-clean
	echo done
	cd memory && \
	$(MAKE) dist-clean
	echo done
	cd gui && \
	$(MAKE) dist-clean
	echo done
	cd disasm && \
	$(MAKE) dist-clean
	echo done
	cd instrument/stubs && \
	$(MAKE) dist-clean
	echo done
	cd misc && \
	$(MAKE) dist-clean
	echo done
	cd dynamic && \
	$(MAKE) dist-clean
	echo done
	cd fpu && \
	$(MAKE) dist-clean
	echo done
	rm -f  Makefile
